// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJk3g7eUQ454KxfqmX5zVNuqLwVBPGlmk',
    appId: '1:825506978982:web:4f24057c6e36a42396e867',
    messagingSenderId: '825506978982',
    projectId: 'region-skane-fire',
    authDomain: 'region-skane-fire.firebaseapp.com',
    storageBucket: 'region-skane-fire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX0se8frDXyXaQ4wZkjfMxMkaK2JuK0vk',
    appId: '1:825506978982:android:28a12e8885dd394c96e867',
    messagingSenderId: '825506978982',
    projectId: 'region-skane-fire',
    storageBucket: 'region-skane-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtGadmvMAwbBjvHaDZ-3q9VRTwObm5BIQ',
    appId: '1:825506978982:ios:14e94e224e4e872596e867',
    messagingSenderId: '825506978982',
    projectId: 'region-skane-fire',
    storageBucket: 'region-skane-fire.appspot.com',
    iosBundleId: 'com.example.flutterLocalTestPca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtGadmvMAwbBjvHaDZ-3q9VRTwObm5BIQ',
    appId: '1:825506978982:ios:b479ebc4a7bfc4ff96e867',
    messagingSenderId: '825506978982',
    projectId: 'region-skane-fire',
    storageBucket: 'region-skane-fire.appspot.com',
    iosBundleId: 'com.example.flutterLocalTestPca.RunnerTests',
  );
}
